@startuml

title __UTILS's Class Diagram__\n

  namespace com.kamshanski.blepositioning {
    namespace utils {
      class com.kamshanski.blepositioning.utils.RandomRssiGenerator {
          {static} + COS : String
          {static} + SIN : String
          {static} + SQR : String
          {static} + TRI : String
          ~ a : double
          ~ bias : double
          ~ fi : double
          ~ form : String
          ~ fr : double
          ~ max : double
          ~ min : double
          ~ random : Random
          ~ t : double
          ~ triA : double
          ~ triFr : double
          + RandomRssiGenerator()
          + fillArray()
          + getArray()
          + next()
          - getLeadingLine()
      }
    }
  }
  

  namespace com.kamshanski.blepositioning {
    namespace utils {
      class com.kamshanski.blepositioning.utils.SquareDimension {
          + xMax : int
          + xMin : int
          + yMax : int
          + yMin : int
          + SquareDimension()
          + fitX()
          + fitY()
      }
    }
  }
  

  namespace com.kamshanski.blepositioning {
    namespace utils {
      class com.kamshanski.blepositioning.utils.U {
          {static} - r : Random
          {static} + invertArray()
          {static} + invertArray()
          {static} + invertArray()
          {static} + invertArray()
          {static} + nout()
          {static} + out()
          {static} + randInt()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
