@startuml

title __COMPORT's Class Diagram__\n

  namespace com.kamshanski.blepositioning {
    namespace comport {
      class com.kamshanski.blepositioning.comport.ComPortConstants {
          {static} + CAPACITY : char[]
          {static} + DEVICE_MAC : char[]
          {static} + ERROR : char[]
          {static} + PAYLOAD : char[]
          {static} + PAYLOAD_LENGTH : int
          {static} + READY : char[]
          {static} + RELOADING : char[]
          {static} + SIZE : char[]
          {static} + SLAVES : char[]
          {static} + TARGET_SET_END : char[]
          {static} + TARGET_SET_START : char[]
          {static} + TIME_END : char[]
          {static} + TIME_START : char[]
      }
    }
  }
  

  namespace com.kamshanski.blepositioning {
    namespace comport {
      class com.kamshanski.blepositioning.comport.ComPortListener {
          + log : DataPropagator<String>
          ~ model : LiveData<Model>
          + ComPortListener()
          + onError()
          + onPayload()
          + onReady()
          + onRestarting()
          + onSlavesNumber()
          + onTargetsSet()
          + onTerminal()
          + println()
      }
    }
  }
  

  namespace com.kamshanski.blepositioning {
    namespace comport {
      class com.kamshanski.blepositioning.comport.ComReader {
          {static} + DEFAULT_CAPACITY : int
          {static} + listeningEvents : int
          - builder : StringBuilder
          - capacityBuf : StringBuilder
          - isOnNewLine : boolean
          - isOpened : boolean
          - macsBuf : StringBuilder
          - portNum : int
          - serialPort : SerialPort
          - sizeBuf : StringBuilder
          - timeEnd : long
          - timeStart : long
          + ComReader()
          + about()
          + close()
          + getListeningEvents()
          + getPortNum()
          + isOpened()
          + open()
          + serialEvent()
          ~ getPortsList()
      }
    }
  }
  

  com.kamshanski.blepositioning.comport.ComReader .up.|> com.fazecast.jSerialComm.SerialPortDataListener
  com.kamshanski.blepositioning.comport.ComReader o-- com.kamshanski.blepositioning.comport.ComPortListener : comPortListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
